apply plugin: 'org.greenrobot.greendao'
apply plugin: 'com.android.application'

def getVersionCode = { ->
    try {
        def stdout = new ByteArrayOutputStream()
        exec {
            commandLine 'git', 'rev-list', '--all', '--count'
            standardOutput = stdout
        }
        return Integer.parseInt(stdout.toString().trim())
    }
    catch (ignored) {
        return -1;
    }
}

def getVersionName = { ->
    try {
        def stdout = new ByteArrayOutputStream()
        exec {
            commandLine 'git', 'rev-parse', '--short', 'HEAD'
            standardOutput = stdout
        }
        return new Date().format("yyyy-MM-dd") + "_" + stdout.toString().trim()
    }
    catch (ignored) {
        return new Date().format("yyyy-MM-dd");
    }
}


android {
    compileSdkVersion 28
    buildToolsVersion '28.0.3'
    defaultConfig {
        applicationId "wang.switchy.hin2n"
        minSdkVersion 17
        targetSdkVersion 28
        versionCode getVersionCode()
        versionName getVersionName()
        multiDexEnabled true
        resConfigs "en", "zh-rCN", "zh-rTW"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
        externalNativeBuild {
            cmake {
                cppFlags ""
                cFlags "-D__ANDROID_NDK__"
            }
        }
    }

    signingConfigs {
        debug {}

        release {
            storeFile file(System.getenv("KEYSTORE_FILE") ?: "Hin2n.jks")
            storePassword System.getenv("KEYSTORE_PASSWORD") ?: "My-Hin2n"
            keyAlias System.getenv("KEY_ALIAS") ?: "Hin2n"
            keyPassword System.getenv("KEY_PASSWORD") ?: (System.getenv("KEYSTORE_PASSWORD") ?: "My-Hin2n")
        }
    }

    buildTypes {
        debug {
            buildConfigField("boolean", "LOG_DEBUG", "true")
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'

        }

        release {
            buildConfigField("boolean", "LOG_DEBUG", "false")
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'

            signingConfig signingConfigs.release
        }
    }

    applicationVariants.all { variant ->
        variant.outputs.all { output ->
            def outputFile = output.outputFile
            if (outputFile != null && outputFile.name.endsWith('.apk')) {
                def versionName = getVersionName()
                output.versionNameOverride = versionName
                def arch = variant.mergedFlavor.manifestPlaceholders.ARCH
                def fileName = "hin2n_${versionName}_${arch}.apk"
                outputFileName = fileName
            }

        }
    }

    flavorDimensions "arch"

    productFlavors {
        arm64 {
            dimension "arch"
            ndk {
                abiFilters "arm64-v8a"
                manifestPlaceholders += [ARCH: "arm64-v8a"]
            }
        }
    }

    externalNativeBuild {
        cmake {
            path "CMakeLists.txt"
        }
    }
    
    compileOptions {
        sourceCompatibility 1.8
        targetCompatibility 1.8
    }
}

greendao {
    schemaVersion 4
    daoPackage 'wang.switchy.hin2n.storage.db.base'
    targetGenDir 'src/main/java'
}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation 'androidx.drawerlayout:drawerlayout:1.0.0'
    androidTestImplementation('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    implementation 'com.github.CymChad:BaseRecyclerViewAdapterHelper:3.0.8'
    implementation 'com.android.support:design:28.0.0'
    testImplementation 'junit:junit:4.12'
    implementation 'com.android.support:appcompat-v7:28.0.0'
    implementation 'org.greenrobot:eventbus:latest.integration'
    implementation 'com.umeng.sdk:common:latest.integration'
    implementation 'com.umeng.sdk:utdid:latest.integration'
    implementation 'com.umeng.sdk:analytics:latest.integration'
    implementation 'org.greenrobot:greendao:3.2.0'
    implementation project(':swipemenulistview')
    implementation project(':AVLoadingIndicatorView')
    implementation 'com.orhanobut:logger:1.15'
    implementation 'com.tencent.bugly:crashreport_upgrade:latest.release'
    implementation 'com.tencent.bugly:nativecrashreport:latest.release'
    implementation files('libs/umeng-share-core-6.9.2.jar')
    implementation files('libs/umeng-share-sina-simplify-6.9.2.jar')
    implementation files('libs/umeng-share-wechat-simplify-6.9.2.jar')
    implementation files('libs/umeng-sharetool-6.9.2.jar')
    implementation project(':AndPermission')
    implementation 'com.github.f0ris.sweetalert:library:latest.release'
}
